### ISSUE TITLE
STM32F4xx Porting

### ISSUE THREAD

**Issue by cutephoton** [lixpaulian/stm32f7-uart#1]
Thanks for posting this driver. I really appreciate the documentation and effort you put in to writing this. :)

This code ports pretty well to F4 series with minor changes. I thought I'd document the that here. (Perhaps I'll post a proper patch with conditional compilation on the MCU family if I get around to it.)

- Disabling cache operations.
- Disabling unsupported features. (7bit wasn't supported in the same way? Also, I disabled the BREAK code and RS485 because I didn't need that.)
- do_tcsetattr -> UART_SetConfig (UART_SetConfig is statically defined, so used _Init _DeInit calls instead - not sure if this has side effects)

All told, it this did not take much time... maybe an hour.

**Comment by lixpaulian** [comment]
Glad it worked for you.

The UART_SetConfig() call is on most STM32Fx HAL drivers, except the F7, declared static. I opened a thread on the ST Community, but it seems they don't have plans to change the situation. Doing the whole Deinit/Init is somehow brutal, but if it works for you, that's ok. I was planing to handle this differently, as I plan myself to extend the driver to other controllers, but the available time doesn't allow me doing it for now.

I am using the driver in many projects without issues.
